#!/bin/ash

. /etc/ext.config

# don't run initialisation  if /tmp/ext_no_auto_ext exists
if [ -e $ext_no_install  ] ; then
   echo "Doesn't run init because $ext_no_install exists "
   exit 0
fi

/etc/init.d/ext init

